/* eslint-disable */
/**
 * KeychainRelyingParty API with Algorand SmartSig delegated access
 * A client for interfacing with the KeychainRelyingParty API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface AssertionResponse
 */
export interface AssertionResponse {
    /**
     * 
     * @type {string}
     * @memberof AssertionResponse
     */
    authenticatorData?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AssertionResponse
     */
    signature?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AssertionResponse
     */
    clientDataJSON?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AssertionResponse
     */
    userHandle?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AssertionResponse
     */
    attestationObject?: string | null;
}
