/* eslint-disable */
/**
 * KeychainRelyingParty API with Algorand SmartSig delegated access
 * A client for interfacing with the KeychainRelyingParty API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AuthenticationExtensionsClientInputs } from './authentication-extensions-client-inputs';
import { Fido2ResponseBase } from './fido2-response-base';
import { PublicKeyCredentialDescriptor } from './public-key-credential-descriptor';
import { UserVerificationRequirement } from './user-verification-requirement';
/**
 * 
 * @export
 * @interface AssertionOptions
 */
export interface AssertionOptions extends Fido2ResponseBase {
    /**
     * 
     * @type {string}
     * @memberof AssertionOptions
     */
    challenge?: string | null;
    /**
     * 
     * @type {number}
     * @memberof AssertionOptions
     */
    timeout?: number;
    /**
     * 
     * @type {string}
     * @memberof AssertionOptions
     */
    rpId?: string | null;
    /**
     * 
     * @type {Array<PublicKeyCredentialDescriptor>}
     * @memberof AssertionOptions
     */
    allowCredentials?: Array<PublicKeyCredentialDescriptor> | null;
    /**
     * 
     * @type {UserVerificationRequirement}
     * @memberof AssertionOptions
     */
    userVerification?: UserVerificationRequirement | null;
    /**
     * 
     * @type {AuthenticationExtensionsClientInputs}
     * @memberof AssertionOptions
     */
    extensions?: AuthenticationExtensionsClientInputs | null;
}
