/* eslint-disable */
/**
 * KeychainRelyingParty API with Algorand SmartSig delegated access
 * A client for interfacing with the KeychainRelyingParty API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AuthenticatorAttachment } from './authenticator-attachment';
import { ResidentKeyRequirement } from './resident-key-requirement';
import { UserVerificationRequirement } from './user-verification-requirement';
/**
 * 
 * @export
 * @interface AuthenticatorSelection
 */
export interface AuthenticatorSelection {
    /**
     * 
     * @type {AuthenticatorAttachment}
     * @memberof AuthenticatorSelection
     */
    authenticatorAttachment?: AuthenticatorAttachment | null;
    /**
     * 
     * @type {ResidentKeyRequirement}
     * @memberof AuthenticatorSelection
     */
    residentKey?: ResidentKeyRequirement;
    /**
     * 
     * @type {boolean}
     * @memberof AuthenticatorSelection
     */
    requireResidentKey?: boolean;
    /**
     * 
     * @type {UserVerificationRequirement}
     * @memberof AuthenticatorSelection
     */
    userVerification?: UserVerificationRequirement;
}
