/* eslint-disable */
/**
 * KeychainRelyingParty API with Algorand SmartSig delegated access
 * A client for interfacing with the KeychainRelyingParty API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface AuthenticationExtensionsDevicePublicKeyInputs
 */
export interface AuthenticationExtensionsDevicePublicKeyInputs {
    /**
     * 
     * @type {string}
     * @memberof AuthenticationExtensionsDevicePublicKeyInputs
     */
    attestation?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof AuthenticationExtensionsDevicePublicKeyInputs
     */
    attestationFormats?: Array<string> | null;
}
