/* eslint-disable */
/**
 * KeychainRelyingParty API with Algorand SmartSig delegated access
 * A client for interfacing with the KeychainRelyingParty API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AttestationConveyancePreference } from './attestation-conveyance-preference';
import { AuthenticationExtensionsClientInputs } from './authentication-extensions-client-inputs';
import { AuthenticatorSelection } from './authenticator-selection';
import { Fido2ResponseBase } from './fido2-response-base';
import { Fido2User } from './fido2-user';
import { PubKeyCredParam } from './pub-key-cred-param';
import { PublicKeyCredentialDescriptor } from './public-key-credential-descriptor';
import { PublicKeyCredentialRpEntity } from './public-key-credential-rp-entity';
/**
 * 
 * @export
 * @interface CredentialCreateOptions
 */
export interface CredentialCreateOptions extends Fido2ResponseBase {
    /**
     * 
     * @type {PublicKeyCredentialRpEntity}
     * @memberof CredentialCreateOptions
     */
    rp?: PublicKeyCredentialRpEntity | null;
    /**
     * 
     * @type {Fido2User}
     * @memberof CredentialCreateOptions
     */
    user?: Fido2User | null;
    /**
     * 
     * @type {string}
     * @memberof CredentialCreateOptions
     */
    challenge?: string | null;
    /**
     * 
     * @type {Array<PubKeyCredParam>}
     * @memberof CredentialCreateOptions
     */
    pubKeyCredParams?: Array<PubKeyCredParam> | null;
    /**
     * 
     * @type {number}
     * @memberof CredentialCreateOptions
     */
    timeout?: number;
    /**
     * 
     * @type {AttestationConveyancePreference}
     * @memberof CredentialCreateOptions
     */
    attestation?: AttestationConveyancePreference;
    /**
     * 
     * @type {AuthenticatorSelection}
     * @memberof CredentialCreateOptions
     */
    authenticatorSelection?: AuthenticatorSelection | null;
    /**
     * 
     * @type {Array<PublicKeyCredentialDescriptor>}
     * @memberof CredentialCreateOptions
     */
    excludeCredentials?: Array<PublicKeyCredentialDescriptor> | null;
    /**
     * 
     * @type {AuthenticationExtensionsClientInputs}
     * @memberof CredentialCreateOptions
     */
    extensions?: AuthenticationExtensionsClientInputs | null;
}
