/* eslint-disable */
/**
 * KeychainRelyingParty API with Algorand SmartSig delegated access
 * A client for interfacing with the KeychainRelyingParty API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AuthenticationExtensionsPRFInputs } from './authentication-extensions-prfinputs';
/**
 * 
 * @export
 * @interface MakeCredentialOptionsModel
 */
export interface MakeCredentialOptionsModel {
    /**
     * 
     * @type {string}
     * @memberof MakeCredentialOptionsModel
     */
    username?: string;
    /**
     * 
     * @type {string}
     * @memberof MakeCredentialOptionsModel
     */
    displayName?: string;
    /**
     * 
     * @type {string}
     * @memberof MakeCredentialOptionsModel
     */
    attType?: string;
    /**
     * 
     * @type {string}
     * @memberof MakeCredentialOptionsModel
     */
    authType?: string;
    /**
     * 
     * @type {string}
     * @memberof MakeCredentialOptionsModel
     */
    residentKey?: string;
    /**
     * 
     * @type {string}
     * @memberof MakeCredentialOptionsModel
     */
    userVerification?: string;
    /**
     * 
     * @type {AuthenticationExtensionsPRFInputs}
     * @memberof MakeCredentialOptionsModel
     */
    prf?: AuthenticationExtensionsPRFInputs | null;
}
