/* eslint-disable */
/**
 * KeychainRelyingParty API with Algorand SmartSig delegated access
 * A client for interfacing with the KeychainRelyingParty API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AuthenticatorAssertionRawResponse } from './authenticator-assertion-raw-response';
import { DWT } from './dwt';
import { Fido2ResponseBase } from './fido2-response-base';
/**
 * 
 * @export
 * @interface MakeAssertionRequestModel
 */
export interface MakeAssertionRequestModel extends Fido2ResponseBase {
    /**
     * 
     * @type {AuthenticatorAssertionRawResponse}
     * @memberof MakeAssertionRequestModel
     */
    clientResponse?: AuthenticatorAssertionRawResponse;
    /**
     * 
     * @type {string}
     * @memberof MakeAssertionRequestModel
     */
    username?: string;
    /**
     * 
     * @type {DWT}
     * @memberof MakeAssertionRequestModel
     */
    dwt?: DWT;
}
