/* eslint-disable */
/**
 * KeychainRelyingParty API with Algorand SmartSig delegated access
 * A client for interfacing with the KeychainRelyingParty API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Algorithm } from './algorithm';
import { PublicKeyCredentialType } from './public-key-credential-type';
/**
 * 
 * @export
 * @interface PubKeyCredParam
 */
export interface PubKeyCredParam {
    /**
     * 
     * @type {PublicKeyCredentialType}
     * @memberof PubKeyCredParam
     */
    type?: PublicKeyCredentialType;
    /**
     * 
     * @type {Algorithm}
     * @memberof PubKeyCredParam
     */
    alg?: Algorithm;
}
