/* eslint-disable */
/**
 * KeychainRelyingParty API with Algorand SmartSig delegated access
 * A client for interfacing with the KeychainRelyingParty API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AuthenticatorTransport } from './authenticator-transport';
import { PublicKeyCredentialType } from './public-key-credential-type';
/**
 * 
 * @export
 * @interface PublicKeyCredentialDescriptor
 */
export interface PublicKeyCredentialDescriptor {
    /**
     * 
     * @type {PublicKeyCredentialType}
     * @memberof PublicKeyCredentialDescriptor
     */
    type?: PublicKeyCredentialType;
    /**
     * 
     * @type {string}
     * @memberof PublicKeyCredentialDescriptor
     */
    id?: string;
    /**
     * 
     * @type {Array<AuthenticatorTransport>}
     * @memberof PublicKeyCredentialDescriptor
     */
    transports?: Array<AuthenticatorTransport> | null;
}
