/* eslint-disable */
/**
 * KeychainRelyingParty API with Algorand SmartSig delegated access
 * A client for interfacing with the KeychainRelyingParty API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Address } from './address';
import { Digest } from './digest';
/**
 * 
 * @export
 * @interface Transaction
 */
export interface Transaction {
    /**
     * 
     * @type {string}
     * @memberof Transaction
     */
    lease?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Transaction
     */
    note?: string | null;
    /**
     * 
     * @type {number}
     * @memberof Transaction
     */
    confirmedRound?: number | null;
    /**
     * 
     * @type {boolean}
     * @memberof Transaction
     */
    committed?: boolean;
    /**
     * 
     * @type {number}
     * @memberof Transaction
     */
    receiverRewards?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Transaction
     */
    senderRewards?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Transaction
     */
    closeRewards?: number | null;
    /**
     * 
     * @type {string}
     * @memberof Transaction
     */
    poolError?: string | null;
    /**
     * 
     * @type {number}
     * @memberof Transaction
     */
    fee?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Transaction
     */
    firstValid?: number | null;
    /**
     * 
     * @type {string}
     * @memberof Transaction
     */
    genesisId?: string | null;
    /**
     * 
     * @type {Digest}
     * @memberof Transaction
     */
    genesisHash?: Digest | null;
    /**
     * 
     * @type {Digest}
     * @memberof Transaction
     */
    group?: Digest | null;
    /**
     * 
     * @type {number}
     * @memberof Transaction
     */
    lastValid?: number | null;
    /**
     * 
     * @type {Address}
     * @memberof Transaction
     */
    rekeyTo?: Address | null;
    /**
     * 
     * @type {Address}
     * @memberof Transaction
     */
    sender?: Address | null;
}
