/* eslint-disable */
/**
 * KeychainRelyingParty API with Algorand SmartSig delegated access
 * A client for interfacing with the KeychainRelyingParty API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { LSIGSignOptionsModel } from '../models';
/**
 * LSIGSigningApi - axios parameter creator
 * @export
 */
export const LSIGSigningApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {LSIGSignOptionsModel} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        lSIGSigningLSIGSignTransaction: async (body: LSIGSignOptionsModel, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling lSIGSigningLSIGSignTransaction.');
            }
            const localVarPath = `/LSIGSignTransaction`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * LSIGSigningApi - functional programming interface
 * @export
 */
export const LSIGSigningApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @param {LSIGSignOptionsModel} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async lSIGSigningLSIGSignTransaction(body: LSIGSignOptionsModel, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<string>>> {
            const localVarAxiosArgs = await LSIGSigningApiAxiosParamCreator(configuration).lSIGSigningLSIGSignTransaction(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * LSIGSigningApi - factory interface
 * @export
 */
export const LSIGSigningApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @param {LSIGSignOptionsModel} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async lSIGSigningLSIGSignTransaction(body: LSIGSignOptionsModel, options?: AxiosRequestConfig): Promise<AxiosResponse<string>> {
            return LSIGSigningApiFp(configuration).lSIGSigningLSIGSignTransaction(body, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * LSIGSigningApi - object-oriented interface
 * @export
 * @class LSIGSigningApi
 * @extends {BaseAPI}
 */
export class LSIGSigningApi extends BaseAPI {
    /**
     * 
     * @param {LSIGSignOptionsModel} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LSIGSigningApi
     */
    public async lSIGSigningLSIGSignTransaction(body: LSIGSignOptionsModel, options?: AxiosRequestConfig) : Promise<AxiosResponse<string>> {
        return LSIGSigningApiFp(this.configuration).lSIGSigningLSIGSignTransaction(body, options).then((request) => request(this.axios, this.basePath));
    }
}
