/* tslint:disable */
/* eslint-disable */
/**
 * KeychainRelyingParty API with Algorand SmartSig delegated access
 * A client for interfacing with the KeychainRelyingParty API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @enum {string}
 */
export enum Algorithm {
    RS1 = 'RS1',
    RS512 = 'RS512',
    RS384 = 'RS384',
    RS256 = 'RS256',
    ES256K = 'ES256K',
    PS512 = 'PS512',
    PS384 = 'PS384',
    PS256 = 'PS256',
    ES512 = 'ES512',
    ES384 = 'ES384',
    EdDSA = 'EdDSA',
    ES256 = 'ES256'
}

