/* tslint:disable */
/* eslint-disable */
/**
 * KeychainRelyingParty API with Algorand SmartSig delegated access
 * A client for interfacing with the KeychainRelyingParty API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Fido2ResponseBase } from './fido2-response-base';
import { VerifyAssertionResult } from './verify-assertion-result';
/**
 * 
 * @export
 * @interface AssertionResponseModel
 */
export interface AssertionResponseModel extends Fido2ResponseBase {
    /**
     * 
     * @type {VerifyAssertionResult}
     * @memberof AssertionResponseModel
     */
    verifyAssertionResult?: VerifyAssertionResult;
    /**
     * 
     * @type {string}
     * @memberof AssertionResponseModel
     */
    code?: string | null;
}
