/* tslint:disable */
/* eslint-disable */
/**
 * KeychainRelyingParty API with Algorand SmartSig delegated access
 * A client for interfacing with the KeychainRelyingParty API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AuthenticationExtensionsPRFValues } from './authentication-extensions-prfvalues';
/**
 * 
 * @export
 * @interface AuthenticationExtensionsPRFOutputs
 */
export interface AuthenticationExtensionsPRFOutputs {
    /**
     * 
     * @type {boolean}
     * @memberof AuthenticationExtensionsPRFOutputs
     */
    enabled?: boolean;
    /**
     * 
     * @type {AuthenticationExtensionsPRFValues}
     * @memberof AuthenticationExtensionsPRFOutputs
     */
    results?: AuthenticationExtensionsPRFValues | null;
}
