/* tslint:disable */
/* eslint-disable */
/**
 * KeychainRelyingParty API with Algorand SmartSig delegated access
 * A client for interfacing with the KeychainRelyingParty API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AuthenticatorAttestationRawResponse } from './authenticator-attestation-raw-response';
import { DWT } from './dwt';
import { Fido2ResponseBase } from './fido2-response-base';
/**
 * 
 * @export
 * @interface MakeCredentialsRequestModel
 */
export interface MakeCredentialsRequestModel extends Fido2ResponseBase {
    /**
     * 
     * @type {string}
     * @memberof MakeCredentialsRequestModel
     */
    username?: string;
    /**
     * 
     * @type {string}
     * @memberof MakeCredentialsRequestModel
     */
    emailCode?: string;
    /**
     * 
     * @type {DWT}
     * @memberof MakeCredentialsRequestModel
     */
    dwt?: DWT;
    /**
     * 
     * @type {string}
     * @memberof MakeCredentialsRequestModel
     */
    state?: string;
    /**
     * 
     * @type {string}
     * @memberof MakeCredentialsRequestModel
     */
    codeChallenge?: string;
    /**
     * 
     * @type {string}
     * @memberof MakeCredentialsRequestModel
     */
    redirectUri?: string;
    /**
     * 
     * @type {AuthenticatorAttestationRawResponse}
     * @memberof MakeCredentialsRequestModel
     */
    attestationResponse?: AuthenticatorAttestationRawResponse;
}
