/* tslint:disable */
/* eslint-disable */
/**
 * KeychainRelyingParty API with Algorand SmartSig delegated access
 * A client for interfacing with the KeychainRelyingParty API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CredentialMakeResult } from './credential-make-result';
/**
 * 
 * @export
 * @interface MakeCredentialResponse
 */
export interface MakeCredentialResponse {
    /**
     * 
     * @type {CredentialMakeResult}
     * @memberof MakeCredentialResponse
     */
    fidoCredentialMakeResult?: CredentialMakeResult;
    /**
     * 
     * @type {string}
     * @memberof MakeCredentialResponse
     */
    code?: string;
}
