/* tslint:disable */
/* eslint-disable */
/**
 * KeychainRelyingParty API with Algorand SmartSig delegated access
 * A client for interfacing with the KeychainRelyingParty API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AuthenticatorTransport } from './authenticator-transport';
import { Fido2ResponseBase } from './fido2-response-base';
import { Fido2User } from './fido2-user';
import { PublicKeyCredentialType } from './public-key-credential-type';
/**
 * 
 * @export
 * @interface RegisteredPublicKeyCredential
 */
export interface RegisteredPublicKeyCredential extends Fido2ResponseBase {
    /**
     * 
     * @type {PublicKeyCredentialType}
     * @memberof RegisteredPublicKeyCredential
     */
    type?: PublicKeyCredentialType;
    /**
     * 
     * @type {string}
     * @memberof RegisteredPublicKeyCredential
     */
    id?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RegisteredPublicKeyCredential
     */
    publicKey?: string | null;
    /**
     * 
     * @type {Array<AuthenticatorTransport>}
     * @memberof RegisteredPublicKeyCredential
     */
    transports?: Array<AuthenticatorTransport> | null;
    /**
     * 
     * @type {number}
     * @memberof RegisteredPublicKeyCredential
     */
    signCount?: number;
    /**
     * 
     * @type {boolean}
     * @memberof RegisteredPublicKeyCredential
     */
    isBackupEligible?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof RegisteredPublicKeyCredential
     */
    isBackedUp?: boolean;
    /**
     * 
     * @type {string}
     * @memberof RegisteredPublicKeyCredential
     */
    devicePublicKey?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RegisteredPublicKeyCredential
     */
    aaGuid?: string;
    /**
     * 
     * @type {Fido2User}
     * @memberof RegisteredPublicKeyCredential
     */
    user?: Fido2User | null;
    /**
     * 
     * @type {string}
     * @memberof RegisteredPublicKeyCredential
     */
    attestationFormat?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RegisteredPublicKeyCredential
     */
    attestationObject?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RegisteredPublicKeyCredential
     */
    attestationClientDataJson?: string | null;
}
