/* tslint:disable */
/* eslint-disable */
/**
 * ArgonRelyingParty API with Algorand SmartSig delegated access
 * A client for interfacing with the ArgonRelyingParty API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AuthenticationExtensionsDevicePublicKeyOutputs } from './authentication-extensions-device-public-key-outputs';
import { AuthenticationExtensionsPRFOutputs } from './authentication-extensions-prfoutputs';
import { CredentialPropertiesOutput } from './credential-properties-output';
/**
 * 
 * @export
 * @interface AuthenticationExtensionsClientOutputs
 */
export interface AuthenticationExtensionsClientOutputs {
    /**
     * 
     * @type {any}
     * @memberof AuthenticationExtensionsClientOutputs
     */
    exampleExtensionBool?: any | null;
    /**
     * 
     * @type {boolean}
     * @memberof AuthenticationExtensionsClientOutputs
     */
    appid?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof AuthenticationExtensionsClientOutputs
     */
    authnSel?: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof AuthenticationExtensionsClientOutputs
     */
    exts?: Array<string> | null;
    /**
     * 
     * @type {Array<Array<number>>}
     * @memberof AuthenticationExtensionsClientOutputs
     */
    uvm?: Array<Array<number>> | null;
    /**
     * 
     * @type {AuthenticationExtensionsDevicePublicKeyOutputs}
     * @memberof AuthenticationExtensionsClientOutputs
     */
    devicePubKey?: AuthenticationExtensionsDevicePublicKeyOutputs | null;
    /**
     * 
     * @type {CredentialPropertiesOutput}
     * @memberof AuthenticationExtensionsClientOutputs
     */
    credProps?: CredentialPropertiesOutput | null;
    /**
     * 
     * @type {AuthenticationExtensionsPRFOutputs}
     * @memberof AuthenticationExtensionsClientOutputs
     */
    prf?: AuthenticationExtensionsPRFOutputs | null;
}
