/* tslint:disable */
/* eslint-disable */
/**
 * ArgonRelyingParty API with Algorand SmartSig delegated access
 * A client for interfacing with the ArgonRelyingParty API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AuthenticationExtensionsDevicePublicKeyInputs } from './authentication-extensions-device-public-key-inputs';
import { AuthenticationExtensionsPRFInputs } from './authentication-extensions-prfinputs';
/**
 * 
 * @export
 * @interface AuthenticationExtensionsClientInputs
 */
export interface AuthenticationExtensionsClientInputs {
    /**
     * 
     * @type {any}
     * @memberof AuthenticationExtensionsClientInputs
     */
    exampleExtensionBool?: any | null;
    /**
     * 
     * @type {string}
     * @memberof AuthenticationExtensionsClientInputs
     */
    appid?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof AuthenticationExtensionsClientInputs
     */
    authnSel?: Array<string> | null;
    /**
     * 
     * @type {boolean}
     * @memberof AuthenticationExtensionsClientInputs
     */
    exts?: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof AuthenticationExtensionsClientInputs
     */
    uvm?: boolean | null;
    /**
     * 
     * @type {AuthenticationExtensionsDevicePublicKeyInputs}
     * @memberof AuthenticationExtensionsClientInputs
     */
    devicePubKey?: AuthenticationExtensionsDevicePublicKeyInputs | null;
    /**
     * 
     * @type {boolean}
     * @memberof AuthenticationExtensionsClientInputs
     */
    credProps?: boolean | null;
    /**
     * 
     * @type {AuthenticationExtensionsPRFInputs}
     * @memberof AuthenticationExtensionsClientInputs
     */
    prf?: AuthenticationExtensionsPRFInputs | null;
}
