/* tslint:disable */
/* eslint-disable */
/**
 * ArgonRelyingParty API with Algorand SmartSig delegated access
 * A client for interfacing with the ArgonRelyingParty API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface DWT
 */
export interface DWT {
    /**
     * 
     * @type {string}
     * @memberof DWT
     */
    cspk?: string;
    /**
     * 
     * @type {string}
     * @memberof DWT
     */
    credpk?: string | null;
    /**
     * 
     * @type {number}
     * @memberof DWT
     */
    exp?: number;
    /**
     * 
     * @type {string}
     * @memberof DWT
     */
    user?: string;
    /**
     * 
     * @type {string}
     * @memberof DWT
     */
    rand?: string;
    /**
     * 
     * @type {string}
     * @memberof DWT
     */
    hash?: string;
    /**
     * 
     * @type {string}
     * @memberof DWT
     */
    credSig?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DWT
     */
    authenticatorData?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DWT
     */
    clientDataJSON?: string | null;
}
