/* tslint:disable */
/* eslint-disable */
/**
 * ArgonRelyingParty API with Algorand SmartSig delegated access
 * A client for interfacing with the ArgonRelyingParty API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Fido2User
 */
export interface Fido2User {
    /**
     * 
     * @type {string}
     * @memberof Fido2User
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Fido2User
     */
    id?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Fido2User
     */
    displayName?: string | null;
}
