/* tslint:disable */
/* eslint-disable */
/**
 * ArgonRelyingParty API with Algorand SmartSig delegated access
 * A client for interfacing with the ArgonRelyingParty API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Fido2ResponseBase } from './fido2-response-base';
/**
 * 
 * @export
 * @interface GetExchangeCodeRequestModel
 */
export interface GetExchangeCodeRequestModel extends Fido2ResponseBase {
    /**
     * 
     * @type {string}
     * @memberof GetExchangeCodeRequestModel
     */
    code?: string;
    /**
     * 
     * @type {string}
     * @memberof GetExchangeCodeRequestModel
     */
    state?: string;
    /**
     * 
     * @type {string}
     * @memberof GetExchangeCodeRequestModel
     */
    codeVerifier?: string;
    /**
     * 
     * @type {string}
     * @memberof GetExchangeCodeRequestModel
     */
    redirectUri?: string;
    /**
     * 
     * @type {string}
     * @memberof GetExchangeCodeRequestModel
     */
    clientId?: string;
    /**
     * 
     * @type {string}
     * @memberof GetExchangeCodeRequestModel
     */
    clientSecret?: string;
}
