/* tslint:disable */
/* eslint-disable */
/**
 * ArgonRelyingParty API with Algorand SmartSig delegated access
 * A client for interfacing with the ArgonRelyingParty API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface PublicKeyCredentialRpEntity
 */
export interface PublicKeyCredentialRpEntity {
    /**
     * 
     * @type {string}
     * @memberof PublicKeyCredentialRpEntity
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof PublicKeyCredentialRpEntity
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof PublicKeyCredentialRpEntity
     */
    icon?: string | null;
}
