/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { InlineResponse200 } from '../models';
/**
 * WebauthnLSIGApi - axios parameter creator
 * @export
 */
export const WebauthnLSIGApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Get the LSIG for a given Webauthn credential
         * @param {any} credpk 
         * @param {any} origin 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getGetWebauthnLSIG: async (credpk: any, origin: any, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'credpk' is not null or undefined
            if (credpk === null || credpk === undefined) {
                throw new RequiredError('credpk','Required parameter credpk was null or undefined when calling getGetWebauthnLSIG.');
            }
            // verify required parameter 'origin' is not null or undefined
            if (origin === null || origin === undefined) {
                throw new RequiredError('origin','Required parameter origin was null or undefined when calling getGetWebauthnLSIG.');
            }
            const localVarPath = `/api/webauthnlsig/{credpk}/{origin}`
                .replace(`{${"credpk"}}`, encodeURIComponent(String(credpk)))
                .replace(`{${"origin"}}`, encodeURIComponent(String(origin)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * WebauthnLSIGApi - functional programming interface
 * @export
 */
export const WebauthnLSIGApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Get the LSIG for a given Webauthn credential
         * @param {any} credpk 
         * @param {any} origin 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getGetWebauthnLSIG(credpk: any, origin: any, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<InlineResponse200>>> {
            const localVarAxiosArgs = await WebauthnLSIGApiAxiosParamCreator(configuration).getGetWebauthnLSIG(credpk, origin, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * WebauthnLSIGApi - factory interface
 * @export
 */
export const WebauthnLSIGApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary Get the LSIG for a given Webauthn credential
         * @param {any} credpk 
         * @param {any} origin 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getGetWebauthnLSIG(credpk: any, origin: any, options?: AxiosRequestConfig): Promise<AxiosResponse<InlineResponse200>> {
            return WebauthnLSIGApiFp(configuration).getGetWebauthnLSIG(credpk, origin, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * WebauthnLSIGApi - object-oriented interface
 * @export
 * @class WebauthnLSIGApi
 * @extends {BaseAPI}
 */
export class WebauthnLSIGApi extends BaseAPI {
    /**
     * 
     * @summary Get the LSIG for a given Webauthn credential
     * @param {any} credpk 
     * @param {any} origin 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WebauthnLSIGApi
     */
    public async getGetWebauthnLSIG(credpk: any, origin: any, options?: AxiosRequestConfig) : Promise<AxiosResponse<InlineResponse200>> {
        return WebauthnLSIGApiFp(this.configuration).getGetWebauthnLSIG(credpk, origin, options).then((request) => request(this.axios, this.basePath));
    }
}
